# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
